// This file was autogenerated by /home/lucho/work/projects/cursodeconducir/webapp/build/closure/depswriter.py.
// Please do not edit.
goog.addDependency('../../../jsgen/allTests.soy.js', ['cursoconducir.allTests'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../jsgen/menu.soy.js', ['cursoconducir.menu'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../jslib/lib/bootstrap-modal.js', ['bootstrap.modal'], ['jquery']);
goog.addDependency('../../../jslib/lib/bootstrap-popover.js', ['bootstrap.popover'], []);
goog.addDependency('../../../jslib/lib/bootstrap-twipsy.js', ['bootstrap.twipsy'], []);
goog.addDependency('../../../jslib/lib/hashchange.js', ['hashchange'], ['jquery']);
goog.addDependency('../../../jslib/lib/jquery.js', ['jquery'], []);
goog.addDependency('../../../jslib/lib/jquery.querystring.js', ['jquery.querystring'], ['jquery']);
goog.addDependency('../../../jslib/lib/jquery.wysiwyg.js', ['jquery.wysiwyg'], ['jquery']);
goog.addDependency('../../../jslib/lib/json.js', ['portableJson'], []);
goog.addDependency('../../../jslib/lib/mustache.jquery.js', ['jquery.mustache'], ['jquery', 'mustache']);
goog.addDependency('../../../jslib/lib/mustache.js', ['mustache'], []);
goog.addDependency('../../../jslib/lib/soyutils.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../modules/allTests.js', ['cursoconducir.AllTestsModule'], ['cursoconducir.allTests', 'goog.soy', 'jquery.mustache']);
goog.addDependency('../../../modules/test.js', ['cursoconducir.TestModule'], ['bootstrap.modal', 'cursoconducir.utils', 'jquery.wysiwyg', 'portableJson']);
goog.addDependency('../../../modules/testPreview.js', ['cursoconducir.TestPreviewModule'], ['jquery.mustache']);
goog.addDependency('../../../modules/utils/utils.js', ['cursoconducir.utils'], []);
goog.addDependency('../../../pages/admin/tests.js', ['cursoconducir.admin.TestsPage', 'cursoconducir.admin.tests'], ['cursoconducir.AllTestsModule', 'cursoconducir.TestModule', 'cursoconducir.TestPreviewModule', 'cursoconducir.utils', 'goog.net.Cookies', 'hashchange', 'jquery.querystring']);
goog.addDependency('../../../pages/index.js', ['cursoconducir.IndexPage', 'cursoconducir.index'], ['bootstrap.modal', 'cursoconducir.TestPreviewModule', 'cursoconducir.utils', 'goog.net.Cookies', 'hashchange', 'jquery', 'jquery.querystring']);
