// This file was autogenerated by /home/lucho/work/projects/cursodeconducir/webapp/build/closure/depswriter.py.
// Please do not edit.
goog.addDependency('../../../jslib/bootstrap-modal.js', ['bootstrap.modal'], ['jquery']);
goog.addDependency('../../../jslib/bootstrap-popover.js', ['bootstrap.popover'], []);
goog.addDependency('../../../jslib/bootstrap-twipsy.js', ['bootstrap.twipsy'], []);
goog.addDependency('../../../jslib/closure/goog/base.js', ['goog'], []);
goog.addDependency('../../../jslib/hashchange.js', ['hashchange'], ['jquery']);
goog.addDependency('../../../jslib/jquery.js', ['jquery'], []);
goog.addDependency('../../../jslib/jquery.querystring.js', ['jquery.querystring'], ['jquery']);
goog.addDependency('../../../jslib/jquery.wysiwyg.js', ['jquery.wysiwyg'], ['jquery']);
goog.addDependency('../../../jslib/json.js', ['portableJson'], []);
goog.addDependency('../../../jslib/mustache.jquery.js', ['jquery.mustache'], ['jquery', 'mustache']);
goog.addDependency('../../../jslib/mustache.js', ['mustache'], []);
goog.addDependency('../../../modules/allTests.js', ['cursoconducir.AllTestsModule'], ['jquery.mustache']);
goog.addDependency('../../../modules/test.js', ['cursoconducir.TestModule'], ['bootstrap.modal', 'cursoconducir.utils', 'jquery.wysiwyg', 'portableJson']);
goog.addDependency('../../../modules/testPreview.js', ['cursoconducir.TestPreviewModule'], ['jquery.mustache']);
goog.addDependency('../../../modules/utils/utils.js', ['cursoconducir.utils'], []);
goog.addDependency('../../../pages/admin/tests.js', ['cursoconducir.admin.TestsPage'], ['cursoconducir.AllTestsModule', 'cursoconducir.TestModule', 'cursoconducir.TestPreviewModule', 'cursoconducir.utils', 'hashchange', 'jquery.querystring']);
goog.addDependency('../../../pages/index.js', ['cursoconducir.IndexPage'], ['bootstrap.modal', 'cursoconducir.TestPreviewModule', 'cursoconducir.utils', 'hashchange', 'jquery', 'jquery.querystring']);
