// This file was autogenerated by build/closure/depswriter.py.
// Please do not edit.
goog.addDependency('../../../jslib/bootstrap-modal.js', ['bootstrap.modal'], []);
goog.addDependency('../../../jslib/bootstrap-popover.js', ['bootstrap.popover'], []);
goog.addDependency('../../../jslib/bootstrap-twipsy.js', ['bootstrap.twipsy'], []);
goog.addDependency('../../../jslib/closure/goog/base.js', ['goog'], []);
goog.addDependency('../../../jslib/hashchange.js', ['hashchange'], []);
goog.addDependency('../../../jslib/jquery.getQueryString.js', ['jquery'], []);
goog.addDependency('../../../jslib/jquery.js', ['jquery'], []);
goog.addDependency('../../../jslib/jquery.wysiwyg.js', ['jquery.wysiwyg'], ['jquery']);
goog.addDependency('../../../jslib/json.js', ['portableJson'], []);
goog.addDependency('../../../jslib/mustache.js', ['mustache'], []);
goog.addDependency('../../../modules/allTests.js', ['cursoconducir.AllTestsModule'], []);
goog.addDependency('../../../modules/test.js', ['cursoconducir.TestModule'], ['cursoconducir.utils', 'jquery.wysiwyg']);
goog.addDependency('../../../modules/testPreview.js', ['cursoconducir.TestPreviewModule'], []);
goog.addDependency('../../../modules/utils/utils.js', ['cursoconducir.utils'], []);
goog.addDependency('../../../pages/admin/tests.js', ['cursoconducir.admin.TestsPage'], ['cursoconducir.AllTestsModule', 'cursoconducir.TestModule', 'cursoconducir.TestPreviewModule', 'cursoconducir.utils']);
goog.addDependency('../../../pages/index.js', ['cursoconducir.IndexPage'], ['cursoconducir.TestPreviewModule', 'cursoconducir.utils']);
